title: Comunidade do Livro
description: Um grupo contínuo de reflexão sobre edição e mercado editorial.

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - publicar.ps1
  - publicar.cmd
  - README.md
